### ISSUE TITLE
TransformAutoConfiguration类中onApplicationEvent方法内业务代码有什么特殊意义？没有它程序也可以正常运行？

### ISSUE THREAD

**Issue by greamrod** [Robot-L/translator#15]
这一串代码的有什么意义是什么?没有它程序也可以正常运行？如下图：
![xxxxx](https://github.com/user-attachments/assets/1f123c54-4aa2-4135-a71b-52c57dcd61c5)

**Comment by luo-zhan** [comment]
这个是给自定义数据字典转换器用的，可以参考wiki：[字典转换器](https://github.com/luo-zhan/Transformer/wiki/%E6%95%B0%E6%8D%AE%E5%AD%97%E5%85%B8%E8%BD%AC%E6%8D%A2%20@TransformDict)
