### ISSUE TITLE
hi,我在 Controller.中的方法上添加了 @Translator ,但是在return 的时候封装了CommResponse,所以就不会生效了..

### ISSUE THREAD

**Issue by myucxy** [Robot-L/translator#2]
`@Translator
    @RequestMapping(value = "getOrderList.action")
    public Object getOrderList(@RequestBody CfetsTradeXbondVO cfetsTradeXbondVO) {
        try {
            CfetsTradeXbondPO cfetsTradeXbondPO = XbondBeanCopyCommonMapper.INSTANCE.xbondPOFromVO(cfetsTradeXbondVO);
            List<CfetsTradeXbondPO> cfetsTradeXbondPOList = cfetsTradeXbondCommonService.getOrderList(cfetsTradeXbondPO);

            List<CfetsTradeXbondVO> cfetsTradeXbondVOList = XbondBeanCopyCommonMapper.INSTANCE.xbondPOListToVOList(cfetsTradeXbondPOList);
//            return  cfetsTradeXbondVOList;
            return CommResponse.success(cfetsTradeXbondVOList);
        } catch (Exception e) {
            return CommResponse.failure(e);
        }
    }`

**Comment by myucxy** [comment]
我又解决了... 在Translator 中
if(origin instanceof CommResponse){
            return (T) parse((List) ((CommResponse) origin).getData(), clazz);
        }

**Comment by Robot-L** [comment]
sry, 一直没看邮件，原来改留了两个issues，哈哈。
你这种情况是可以自己特殊处理下，也可以把`@Translator`注解加在service层

**Comment by luo-zhan** [comment]
哈喽，2.0发布了，你的问题已经在新版中解决了哦，通过自定义解包器实现`UnWrapper`接口并注册到spring容器，即可支持返回值类型是包装类的场景~
以下`ResultWrapper`就类似于你的`CommResponse`
```java
    @Bean
    public ResultUnWrapper resultUnWrapper() {
        return new ResultUnWrapper();
    }

    /**
     * 注册ResultWrapper的解包器
     */
    public static class ResultUnWrapper implements UnWrapper<ResultWrapper<?>> {
        @Override
        public Object unWrap(ResultWrapper<?> source) {
            Object data = source.getData();
            if (data instanceof IPage) {
                return ((IPage<?>) data).getRecords();
            }
            // List或bean直接返回
            return data;
        }
    }
```
